# Generated by Django 4.2.27 on 2025-12-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedfile',
            name='original_filename',
            field=models.CharField(blank=True, default='', help_text='Clean filename shown to user (e.g., "song.mp3")', max_length=500),
        ),
    ]
