# Generated by Django 5.2.9 on 2025-12-21 09:14

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF')], db_index=True, max_length=10)),
                ('operation_type', models.CharField(choices=[('convert', 'Convert'), ('trim', 'Trim'), ('merge', 'Merge'), ('split', 'Split'), ('compress', 'Compress'), ('extract', 'Extract'), ('rotate', 'Rotate'), ('protect', 'Protect'), ('unlock', 'Unlock'), ('reorder', 'Reorder'), ('delete_pages', 'Delete Pages')], default='convert', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('input_file', models.FileField(max_length=500, upload_to=apps.core.models.upload_path)),
                ('output_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.models.output_path)),
                ('input_format', models.CharField(max_length=20)),
                ('output_format', models.CharField(max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds (for audio/video)', null=True)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Additional conversion options like start_time, end_time, quality, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Conversion Job',
                'verbose_name_plural': 'Conversion Jobs',
                'db_table': 'conversion_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'tool_type'], name='conversion__status_111754_idx'), models.Index(fields=['client_ip', 'created_at'], name='conversion__client__b4d4e6_idx'), models.Index(fields=['tool_type', 'operation_type'], name='conversion__tool_ty_968a58_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_file', models.FileField(max_length=500, upload_to=apps.core.models.output_path)),
                ('output_format', models.CharField(max_length=20)),
                ('file_size', models.BigIntegerField(help_text='Output file size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_files', to='core.conversionjob')),
            ],
            options={
                'verbose_name': 'Converted File',
                'verbose_name_plural': 'Converted Files',
                'db_table': 'converted_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='converted_f_expires_3b324d_idx'), models.Index(fields=['conversion_job', 'created_at'], name='converted_f_convers_97b81d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, help_text='Name of the tool used (e.g., audio_convert, video_trim)', max_length=50)),
                ('client_ip', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('conversion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='core.conversionjob')),
            ],
            options={
                'verbose_name': 'Tool Usage Log',
                'verbose_name_plural': 'Tool Usage Logs',
                'db_table': 'tool_usage_logs',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['tool_name', 'used_at'], name='tool_usage__tool_na_449862_idx'), models.Index(fields=['client_ip', 'used_at'], name='tool_usage__client__c3d675_idx'), models.Index(fields=['success', 'used_at'], name='tool_usage__success_b90a47_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(help_text='Original filename from user', max_length=500)),
                ('stored_file', models.FileField(max_length=500, upload_to=apps.core.models.upload_path)),
                ('file_type', models.CharField(db_index=True, help_text='MIME type or file extension', max_length=50)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata (duration, dimensions, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='core.conversionjob')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['file_type', 'uploaded_at'], name='uploaded_fi_file_ty_70afbf_idx')],
            },
        ),
    ]
